name: Pacotinho-backend-CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t paulogalleazzo/pacotinho_do_amor_backend .
      - name: Push image docker
        run: docker push paulogalleazzo/pacotinho_do_amor_backend

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull img from docker hub
        run: docker pull paulogalleazzo/pacotinho_do_amor_backend:latest
      - name: Remove docker container antigo
        run: docker rm -f pacotinho_do_amor_backend
      - name: Run docker container
        run: docker run -d -p 8080:8080 -e AWS_DATABASE_URL=${{secrets.AWS_DATABASE_URL}} -e AWS_DATABASE_PASSWORD='${{secrets.AWS_DATABASE_PASSWORD}}' -e AWS_DATABASE_USER=${{secrets.AWS_DATABASE_USER}} --name pacotinho_do_amor_backend paulogalleazzo/pacotinho_do_amor_backend