name: Pacotinho-backend-CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login --username ${{secrets.DOCKER_USER}} --password-stdin ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t paulogalleazzo/Pacotinho-do-amor-BackEnd .
      - name: Push image docker
        run: docker push paulogalleazzo/Pacotinho-do-amor-BackEnd